# ---- Étape 1 : compiler Angular ----
FROM node:22-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

# L'URL de l'API est fixée AU BUILD (le JS final la contient en dur)
ARG NG_APP_API_URL
ENV NG_APP_API_URL=$NG_APP_API_URL

RUN npx ng build

# ---- Étape 2 : servir les fichiers avec Nginx ----
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/deployment-demo-frontend/browser /usr/share/nginx/html

EXPOSE 80