FROM node:22-alpine

WORKDIR /app
ENV NODE_ENV=production

# npm ci : installation exacte selon package-lock.json (reproductible)
# --omit=dev : sans nodemon ni autres outils de dev
COPY package*.json ./
RUN npm ci --omit=dev

# Cette fois, on COPIE le code dans l'image
COPY src ./src

EXPOSE 3000

# Ne pas tourner en root dans le conteneur (bonne pratique de sécurité)
USER node

CMD ["node", "src/server.js"]